blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/SjxSubham/COntribute-HAcktoX/discussions
    about: Ask questions and discuss ideas with the community
